// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9V_xATzF-wFyW9Q-nRK56CmulEcPCAAw',
    appId: '1:556037439136:web:5afdc780a9eae1c66b93c5',
    messagingSenderId: '556037439136',
    projectId: 'libercopia-book-store-ap-2bb36',
    authDomain: 'libercopia-book-store-ap-2bb36.firebaseapp.com',
    storageBucket: 'libercopia-book-store-ap-2bb36.firebasestorage.app',
    measurementId: 'G-YSL9PGZNHQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7zRwujdhHzqZrapu2JusgxcC2dfQ_PeM',
    appId: '1:556037439136:android:50879749322779576b93c5',
    messagingSenderId: '556037439136',
    projectId: 'libercopia-book-store-ap-2bb36',
    storageBucket: 'libercopia-book-store-ap-2bb36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAxmRnymZ3VNhd6THvhAc53zlnXPNVJFo',
    appId: '1:556037439136:ios:8e40e7b29ced33896b93c5',
    messagingSenderId: '556037439136',
    projectId: 'libercopia-book-store-ap-2bb36',
    storageBucket: 'libercopia-book-store-ap-2bb36.firebasestorage.app',
    androidClientId: '556037439136-bl5s2b3vtgi5oha0v50c3mt129vook1j.apps.googleusercontent.com',
    iosClientId: '556037439136-9kt2vmti08vebnoj3nedmo2un98r4d6a.apps.googleusercontent.com',
    iosBundleId: 'com.example.libercopiaBookstoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAxmRnymZ3VNhd6THvhAc53zlnXPNVJFo',
    appId: '1:556037439136:ios:8e40e7b29ced33896b93c5',
    messagingSenderId: '556037439136',
    projectId: 'libercopia-book-store-ap-2bb36',
    storageBucket: 'libercopia-book-store-ap-2bb36.firebasestorage.app',
    androidClientId: '556037439136-bl5s2b3vtgi5oha0v50c3mt129vook1j.apps.googleusercontent.com',
    iosClientId: '556037439136-9kt2vmti08vebnoj3nedmo2un98r4d6a.apps.googleusercontent.com',
    iosBundleId: 'com.example.libercopiaBookstoreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9V_xATzF-wFyW9Q-nRK56CmulEcPCAAw',
    appId: '1:556037439136:web:a488fab8dd2475db6b93c5',
    messagingSenderId: '556037439136',
    projectId: 'libercopia-book-store-ap-2bb36',
    authDomain: 'libercopia-book-store-ap-2bb36.firebaseapp.com',
    storageBucket: 'libercopia-book-store-ap-2bb36.firebasestorage.app',
    measurementId: 'G-G5CPZQ1XEF',
  );

}